### ISSUE TITLE
Python 2.7 ENV vars not being read from Shell or --env-vars flag

### ISSUE THREAD

**Issue by chrisdevwords** [awslabs/aws-sam-local#104]
Based on the Vote Spaces vs. Tabs example: https://aws.amazon.com/blogs/aws/new-aws-sam-local-beta-build-and-test-serverless-applications-locally/

1. OSX 10.12.6, node 6.9.5, sam version 0.2.0
2. ENV file is localenv.json:
```
{
  "VoteSpacesTabs": {
    "DYNAMODB_ENDPOINT":"http://docker.for.mac.localhost:8010"
  }
}
```
3. template.yaml:
```
AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  VotesTable:
    Type: "AWS::Serverless::SimpleTable"
  VoteSpacesTabs:
    Type: "AWS::Serverless::Function"
    Properties:
      Runtime: python2.7
      Handler: lambda_function.lambda_handler
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref VotesTable
      Events:
        GetVotes:
          Type: Api
          Properties:
            Method: get
            Path: /
        Vote:
          Type: Api
          Properties:
            Path: /
            Method: post

```
4. Python code:
```
table = boto3.resource(
        'dynamodb',
        endpoint_url=environ.get('DYNAMODB_ENDPOINT')
    ).Table('spaces-tabs-votes')
```
5. Running: `sam local start-api --env-vars localenv.json`
6. Running  `DYNAMODB_ENDPOINT=http://docker.for.mac.localhost:8010 sam local start-api`
7. In both cases it tries to connect to the AWS instance of Dynamodb in my machines aws cli creds. When I print the DYNAMODB_ENDPOINT env in the python code, the value is None
8. Setting this value from template.yaml under Environment/Variables works, but I don't want that setting to be present when deployed to AWS.

Am I doing something wrong?

**Comment by tgdavies** [comment]
I'm seeing exactly the same behaviour using the Java8 runtime

**Comment by PaulMaddox** [comment]
It doesn't look like you're specifying the env variable in your SAM template. Environment variables will only be passed through to the function if they are specified in the template.

There are two reasons for this:

1. Without this, SAM Local won't know which of your local environment variables to pass in to your Lambda function. Passing in your whole environment and all variables could be deemed a security risk, so you must specify the ones you want passed in.

2. The idea of changing your function/template between the different stages of development/test/production isn't encouraged. If you want to use DynamoDB Local in your development, then I suggest you parameterise the endpoint url variable like so:

```yaml
Parameters:
  DynamoDBEndpoint:
    Type: String
    Description: Optionally override the DynamoDB endpoint URL

Resources:
VoteSpacesTabs:
    Type: "AWS::Serverless::Function"
    Properties:
      Runtime: python2.7
      Handler: lambda_function.lambda_handler
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          DYNAMODB_ENDPOINT: !Ref DynamoDBEndpoint
          TABLE_NAME: !Ref VotesTable
```

You can then check within your Lambda function whether the environment variable is set or not, and if so, use the overridden endpoint url. This means you will be using the same function code and template between your different environments leading to better consistency.
