### ISSUE TITLE
Internal server error with sam

### ISSUE THREAD

**Issue by alanjjenkins** [awslabs/aws-sam-local#128]
Hey AWS Labs,

I am currently trying to get the simplest possible python function working in sam local start-api.

But it seems that something is breaking sam local start-api (or I am missing something when creating the code) as no matter what I do I get the response:
```
{ "message": "Internal server error" }
```

The template.yml I am using is:

```
---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: My Serverless API

Resources:
  BlogPosts:
    Type: AWS::Serverless::Function
    Properties:
      Handler: test.handler
      Runtime: python3.6
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: get
```

And the current iteration of simple Python code is:

```
def handler(event, context):
    print(event)
    return {'body': 'hello'}
```

The container version is:
```
lambci/lambda                    python3.6           89e54eb9e48e        3 weeks ago         1.08GB
```

And my Docker version is:
```
Docker version 17.07.0-ce, build 87847530f7
```

And my version of sam is:

```
sam version 0.2.0
```

Thanks,

Alan Jenkins
