### ISSUE TITLE
sam validate returns error

### ISSUE THREAD

**Issue by monamu** [awslabs/aws-sam-local#135]
This template file can not validate.

``` yaml
  HelloWorld:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs6.10
      Handler: index.handler
      CodeUri: src/HelloWorld/
      Environment:
        Variables:
          FooKey: "FooValue"
          BazKey: !Sub ["baz value is ${Baz}", { "Baz": "BazValue" }]
      Events:
        Vote:
          Type: Api
          Properties:
            Path: /hello
            Method: get
```

```
$ sam validate
invalid YAML template: json: unsupported type: map[interface {}]interface {}
```

When I remove `BazKey` property, sam returns "Valid!".

Can I use '!Sub' function?
 
```
$ sam --version
sam version 0.2.2
```
