### ISSUE TITLE
Different behaviours on Post method than AWS Lambda/Gateaway

### ISSUE THREAD

**Issue by titouanfreville** [awslabs/aws-sam-local#147]
Hello, I can't seem to find an issue linked to this, if it's a duplicate, sorry for the inconvenience. 

While trying to create a small collector API using AWS Lambda/Gateaway and SAM, I encountered different behaviour on post method when using or not using a parameter. When running SAM local with api-started, in whenever you have a parameter set in the path, you will have an input with a body key whereas in AWS Lambda/Gateaway, you seem to have the body key **only** when a path parameter exist. 

My use case is like: 

- having a collector endpoint under the path: `/collect` who will be used to get data to another part configured with: 
```yaml
  # Collect ------
  Collect:
    Type: AWS::Serverless::Function
    Properties:
      Description: >
        Endpoint to collect data
      Handler: com.bubbles.collector.api.handler.Collect
      Runtime: java8
      MemorySize: 256
      Timeout: 60
      CodeUri: ./target/dmp-collector-dev-shaded.jar
      Role: !GetAtt CollectorRole.Arn
      Events:
        CollectResource:
          Type: Api
          Properties:
            Path: /collect
            Method: post
```

In the template.

- Having an addSchema endpoint to add a json schema to dynamodb table who is configured like this:
```yaml
 # AddSchema ----
  AddSchema:
    Type: AWS::Serverless::Function
    Properties:
      Description: >
        Endpoint to add a new schema
      Handler: com.bubbles.collector.api.handler.Schema
      Runtime: java8
      MemorySize: 256
      Timeout: 60
      CodeUri: ./target/dmp-collector-dev-shaded.jar
      Role: !GetAtt CollectorRole.Arn
      Events:
        AddSchemaResource:
          Type: Api
          Properties:
            Path: /schema/{id}
            Method: post
```

Both of those endpoints provide me with a body key when using sam local to test.
When testing it in AWS Lambda, the add schema add a body key, not the collect one. 

Is it a configuration mistake from my part ? Or did you now this behaviour in AWS ? 

```
❯ sam --version
sam version 0.2.2
```
