### ISSUE TITLE
Globals are not overriding by --env-vars file

### ISSUE THREAD

**Issue by solivaf** [awslabs/aws-sam-local#245]
The template file below defines a funciton called FooBarFunction with globals.
**dev_template.yaml**
```
AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Environment:
      Variables:
        FOO: "B"

Resources:
  FooBarFunction:
    Type: "AWS::Serverless::Function"
    Properties:
      Runtime: python3.6
      Handler: foo.handler
```

This is the content inside my environment file which is passed by --env-vars (-n).
**env.json**
`{
  "FooBarFunction": {
    "FOO": "BAR"
  }
}
`
And this is my function:
```
import os

FOO = os.getenv("FOO")


def handler(event, context):
    print(FOO)

```
These files (template and environment) are in the same folder directory and when I run the command **sam local invoke -n env.json --template dev_template.yaml -e foo.json FooBarFunction** I got None as **print(FOO)** from my handler function
