### ISSUE TITLE
Expecting "int", got "string" on property Timeout on Lambda Function

### ISSUE THREAD

**Issue by yyolk** [awslabs/aws-sam-local#50]
I'm receiving an error when providing a `Timeout` via a `!Ref`

The resource I'm receiving the error on:

```yaml
 CustomAuthorizerLambdaFunction:
   Type: AWS::Serverless::Function
   Properties:
     CodeUri: ./code.jar
     Handler: someClass
     Runtime: java8
     Timeout: !Ref FunctionTimeout
     VpcConfig:
       SecurityGroupIds:
         - !Ref LambdaVPCSecurityGroup
       SubnetIds: !Ref Subnets
     MemorySize: 512
     Environment:
       Variables:
         REDIS_HOST: !Ref RedisHost
         REDIS_PORT: "6379"
         DEFAULT_DB_TIMEOUT: !Ref DBIdleTimeout
     Policies:
       - AWSLambdaVPCAccessExecutionRole
       - AWSXrayWriteOnlyAccess
     Tags:
       Department: engineering
       Application: customer-api
       Service: authorizer-processing
```

the error I receive: 
```
ERROR: Resource "CustomAuthorizerLambdaFunction", property "Timeout": Expecting "int", got "string" (line: 278; col: 6)
```
