### ISSUE TITLE
yaml validation fails for functions with dash in name

### ISSUE THREAD

**Issue by TheDeveloper** [awslabs/aws-sam-local#61]
The following works fine:

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  FunctionName:
      Type: 'AWS::Serverless::Function'
      Properties:
        Handler: index.handler
        Runtime: nodejs6.10
```

But when the function name contains a dash, it produces an error:

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  Function-Name:
      Type: 'AWS::Serverless::Function'
      Properties:
        Handler: index.handler
        Runtime: nodejs6.10
```

```
ERROR: Failed to read the resources line numbers. This usually means that the template contains invalid indentation. Please check it and try again
```
